version: "2"

services:

  # vhosts
  vhosts:
    build:
      context: ./docker/vhosts
      dockerfile: Dockerfile
    restart: always
    container_name: vhosts
    hostname: vhosts
    working_dir: /www
    volumes: 
      - "./www:/www"
      - "./www/logs:/var/log/apache2"
      - "/home/user/.ssh"
    environment:
      ROOT_PASS: root # root
      USER_PASS: user # user
      UID: 1000
      GID: 50
    links:
     - mysql
     - mysql-5.7
     - redis
     - memcached
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"

  # samba
  samba:
    tty: true
    image: dzejson91/vhosts:samba
    restart: always
    container_name: samba
    hostname: samba
    volumes:
      - "./:/data"
      - "./www:/www"
    ports:
      - "139:139"
      - "445:445"

  # portainer
  portainer:
    image: portainer/portainer
    restart: always
    container_name: portainer
    hostname: portainer
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./portainer:/data"
    ports:
      - "9000:9000"
    labels:
      - "hide=hide"

  # database mysql-5.5 (default)
  mysql:
    image: mysql:5.5
    restart: always
    container_name: mysql
    hostname: mysql
    volumes:
      - "./mysql/5.5:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=krasnal
    ports:
      - "3306:3306"

  # database mysql-5.7
  mysql-5.7:
    image: mysql:5.7
    restart: always
    container_name: mysql-5.7
    hostname: mysql-5.7
    volumes:
      - "./mysql/5.7:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=krasnal
    ports:
      - "33306:3306"

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    hostname: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8080:80"
    links: 
      - mysql

  # Cache - Redis
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    hostname: redis
    working_dir: /data
    ports:
      - "6379:6379"
  
  # Cache memcached
  memcached:
    image: memcached:latest
    restart: always
    container_name: memcached
    hostname: memcached
    ports:
      - "11211:11211"